import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { GoogleOAuthProvider } from '@react-oauth/google';
import { Toaster } from 'react-hot-toast';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang="en">
        <body className={inter.className}>
          <GoogleOAuthProvider clientId="721031521118-1rs34m54fd73ds0pn1oa1ocn2f7kb4bp.apps.googleusercontent.com">
            <Toaster />
            {children}
          </GoogleOAuthProvider>
        </body>
      </html>
    </>
  );
}
